import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import SphereGallery from './SphereGallery';
import ARGallery from './ARGallery';
import s from './Gallery.module.css';

/* All photos — small thumb for the marquee/sphere, full-res only in the lightbox */
const RAW_PHOTOS = [
  '/assets/photos/WhatsApp Image 2026-06-15 at 20.32.11 (8).webp',
  '/assets/photos/WhatsApp Image 2026-06-15 at 20.32.11 (1).webp',
  '/assets/photos/WhatsApp Image 2026-06-15 at 20.32.11 (2).webp',
  '/assets/photos/WhatsApp Image 2026-06-15 at 20.32.11 (3).webp',
  '/assets/photos/WhatsApp Image 2026-06-15 at 20.32.11 (4).webp',
  '/assets/photos/WhatsApp Image 2026-06-15 at 20.32.11 (5).webp',
  '/assets/photos/WhatsApp Image 2026-06-15 at 20.32.11 (6).webp',
  '/assets/photos/WhatsApp Image 2026-06-15 at 20.32.11 (7).webp',
  '/assets/photos/WhatsApp Image 2026-06-15 at 20.32.11.webp',
  '/assets/photos/teach-green-poster.webp',
  '/assets/photos/full-classroom.webp',
  '/assets/photos/wll-tshirt.webp',
  '/assets/photos/aerial-group.webp',
  '/assets/photos/blackboard-teach.webp',
  '/assets/photos/class-poster-smile.webp',
  '/assets/photos/group-school.webp',
  '/assets/photos/hug-green.webp',
  '/assets/photos/poster-pair.webp',
  '/assets/photos/volunteer-child.webp',
  '/assets/photos/whiteboard-speak.webp',
  '/assets/vol/vol-01.webp',
  '/assets/vol/vol-02.webp',
  '/assets/vol/vol-03.webp',
  '/assets/vol/vol-04.webp',
  '/assets/vol/vol-05.webp',
  '/assets/vol/vol-06.webp',
  '/assets/vol/vol-07.webp',
  '/assets/vol/vol-08.webp',
  '/assets/vol/vol-09.webp',
  '/assets/vol/vol-10.webp',
  '/assets/vol/vol-11.webp',
  '/assets/vol/vol-12.webp',
  '/assets/vol/vol-13.webp',
];

/* thumb/<filename> holds a small, compressed copy generated by scripts/make-thumbs.mjs */
const ALL_PHOTOS = RAW_PHOTOS.map(full => {
  const i = full.lastIndexOf('/');
  const thumb = `${full.slice(0, i)}/thumb${full.slice(i)}`;
  return { thumb, full };
});

/* Split into 3 rows for the infinite marquee, alternating scroll direction */
const ROWS = [
  { photos: ALL_PHOTOS.filter((_, i) => i % 3 === 0), dir: 'left',  speed: 38 },
  { photos: ALL_PHOTOS.filter((_, i) => i % 3 === 1), dir: 'right', speed: 44 },
  { photos: ALL_PHOTOS.filter((_, i) => i % 3 === 2), dir: 'left',  speed: 50 },
];

function MarqueeRow({ photos, dir, speed, onPick }) {
  // duplicate the row so the loop is seamless
  const doubled = [...photos, ...photos];
  return (
    <div className={s.marqueeRow}>
      <div
        className={`${s.marqueeTrack} ${dir === 'right' ? s.marqueeReverse : ''}`}
        style={{ '--duration': `${speed}s` }}
      >
        {doubled.map((p, i) => (
          <div key={i} className={s.tile} onClick={() => onPick(p.full)}>
            <img src={p.thumb} alt="" loading="lazy" decoding="async" draggable={false} />
          </div>
        ))}
      </div>
    </div>
  );
}

export default function Gallery() {
  const [lightbox, setLightbox] = useState(null);
  const [sphere, setSphere] = useState(false);
  const [ar, setAr] = useState(false);

  return (
    <section className={s.gallery} id="gallery">

      <div className={`shell reveal ${s.head}`}>
        <span className={s.eyebrow}>Moments from WLL</span>
        <h2>Islandwide in Action</h2>
        <p>Real moments from World's Largest Lesson sessions across Sri Lanka.</p>
        <div className={s.galleryBtns}>
          <button className={s.sphereBtn} onClick={() => setSphere(true)}>
            🌐 Explore in 360°
          </button>
          <button className={`${s.sphereBtn} ${s.arBtn}`} onClick={() => setAr(true)}>
            📷 View in AR
          </button>
        </div>
      </div>

      <div className={s.marqueeWrap}>
        {ROWS.map((row, i) => (
          <MarqueeRow key={i} {...row} onPick={setLightbox} />
        ))}
      </div>

      {sphere && <SphereGallery photos={ALL_PHOTOS} onClose={() => setSphere(false)} />}
      {ar && <ARGallery photos={ALL_PHOTOS} onClose={() => setAr(false)} />}

      {/* Aftermovie */}
      <div className={`shell reveal ${s.aftermovie}`}>
        <div className={s.afterHead}>
          <span className={s.eyebrow}>Official Aftermovie</span>
          <h2>World's Largest Lesson in Sri Lanka</h2>
          <p>Relive the energy, impact, and spirit of WLL Sri Lanka from our last edition.</p>
        </div>
        <div className={s.videoWrap}>
          <iframe
            src="https://www.youtube.com/embed/SkMjKQIZbHc"
            title="World's Largest Lesson Sri Lanka Aftermovie"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
            className={s.video}
          />
        </div>
      </div>

      <AnimatePresence>
        {lightbox && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className={s.lightbox}
            onClick={() => setLightbox(null)}
          >
            <motion.div
              initial={{ scale: 0.9, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.9, y: 20 }}
              className={s.lbInner}
              onClick={e => e.stopPropagation()}
            >
              <img src={lightbox} alt="" className={s.lbImg} />
            </motion.div>
            <button className={s.lbClose} onClick={() => setLightbox(null)}>✕</button>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  );
}
